# Generated by Django 5.0.3 on 2024-05-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=7, verbose_name='Скидка в %'),
        ),
    ]
