# Generated by Django 4.2.16 on 2024-11-23 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='discount',
        ),
    ]
