# Generated by Django 4.2.16 on 2024-11-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=7, verbose_name='Скидка в %'),
        ),
    ]
